### ISSUE TITLE
Server boot crash

### ISSUE THREAD

**Issue by SFort** [TeamElysia/Byte-Drives#1] opened 2018-02-18 17:38 UTC
Crash: [Pastebin](https://pastebin.com/xdJLpz23)
bytedrives-v-1.12.2-0.1.0.0
appliedenergistics2-rv5-stable-8
chiselsandbits-14.13

**Comment by TheUnknownFew** [comment] 2018-02-19 10:52
Thank you for this. I'll look into it.

**Comment by TheUnknownFew** [comment] 2018-02-21 11:43
Fixed in the next version of the mod.

**Closed by TheUnknownFew** 2018-02-21 11:43 UTC

**Comment by kreezxil** [comment] 2018-02-28 13:35
got the same thing, saw you said it was fixed a week ago, however the latest version on CurseForge is from Feb 13, can you please push the new mod?

**Comment by TheUnknownFew** [comment] 2018-02-28 19:20
The issue is fixed, yes, however it wont be for another week and a half until i get access to my computer again in order to push the new mod version and its files. The mod and its files are intact, but i had a terrible technical issue with my computer so i cant do anything until that is fixed.
